version: "3.1"

services:
  parkinglot:
    container_name: parkinglot
    restart: always
    build: ./
    ports:
      - 8000:8000
    links:
      - db-postgres
    command: sh -c "npm run db:migrate"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
      - SERVICE_PORT=8000
      - DB_PORT=5432
      - DDB_HOST=db-postgres
      - PGDATA=/data/postgres
    depends_on:
      - db-postgres

  db-postgres:
    container_name: postgres_demo
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
      - PGDATA=/data/postgres
    ports:
      - "5432:5432"


  # redis:
  #   image: "bitnami/redis:latest"
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   ports:
  #     - "6380:6379"


