enum HTTP_STATUS {
    SUCCESS = 200,
    INVALID_REQUEST = 400,
    INTERNAL_SERVER_ERROR = 500,
    SERVICE_NOT_FOUND = 404
}

enum HTTP_MSG {
    SUCCESS = "SUCCESS",
    INVALID_REQUEST = "INVALID_REQUEST",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    SERVICE_NOT_FOUND = "SERVICE_NOT_FOUND"
}

export default { HTTP_MSG, HTTP_STATUS }